Fields and defaults
looplab/logspout-logstash pull request #37
Opened 2016-10-13 16:28 UTC by iljaweis

This adds a new configuration option LOGSTASH_FIELDS for setting any logstash fields, and uses the values of LOGSTASH_FIELDS and LOGSTASH_TAGS for the logspout-logstash as a default for all containers if not set there (see #35).

2016-12-12 12:19 UTC, maxekman requested changes
Thanks for the PR and sorry for the delay! I would be happy to merge this if you could take a look at the comments. It would also be a huge plus if you could add some tests for the fields, there are already some for the tags to get inspired by.

2016-12-12 12:19 UTC, maxekman commented on logstash.go
> +	tags_str := os.Getenv("LOGSTASH_TAGS")
Would be more idiomatic to name this `tagsStr`.

2016-12-12 12:19 UTC, maxekman commented on logstash.go
> +			msg["message"] = m.Data
Please check that `go fmt` has been run correctly.

2016-12-12 12:19 UTC, maxekman commented on logstash.go
> +			for k, v := range fields {
It could be good to blacklist certain keys as to not accidentally overwrite docker, stream, tags etc. What do you think?

2016-12-12 12:19 UTC, maxekman commented on logstash.go
> +			for k, v := range fields {
Same comment as above about a possible key blacklist.

2016-12-29 07:46 UTC, maxekman commented
Do you still want this? If so please respond to the comments.

2017-01-02 10:00 UTC, iljaweis commented
I was off work during the holidays. Yes, I still would like those changes merged. Working on it now.

2017-01-02 11:00 UTC, iljaweis commented on logstash.go
> +			for k, v := range fields {
I can't think of a case where anyone would need to overwrite those fields, and for the tags we already have LOGSTASH_TAGS. So I agree with you here.

2017-01-02 11:01 UTC, iljaweis commented on logstash.go
> +			msg["message"] = m.Data
ok

2017-01-02 11:01 UTC, iljaweis commented on logstash.go
> +	tags_str := os.Getenv("LOGSTASH_TAGS")
ok

2017-01-02 11:10 UTC, iljaweis commented
There are already tests for the fields feature, do you have any specific cases to test in mind?

2017-01-02 12:33 UTC, maxekman commented
No worries, I just did a review of the issues and PRs and wanted to notify the authors. Great that you are picking it up again!

I must have missed the testes, they seem to cover it well.

2017-01-02 14:29 UTC, iljaweis commented
Great. :-) I have since pushed a commit that solves your other comments.

2017-01-03 13:41 UTC, maxekman requested changes
I think with these changes the package will be further simplified!

2017-01-03 13:41 UTC, maxekman commented on logstash.go
> +			msg := make(map[string]interface{})
Now when you are no longer using LogstashMessage you could remove the type entirely and remove duplicate code for both setting the tags and marshalling the message. That would be a nice cleanup and also remove some indentations!

2017-01-03 14:40 UTC, iljaweis commented on logstash.go
> +			msg := make(map[string]interface{})
Ok, I've done that.

2017-01-04 06:52 UTC, maxekman approved these changes
Awesome! Ready to merge?

2017-01-04 07:16 UTC, iljaweis commented
Yes!

2017-01-04 08:45 UTC, merged

2017-01-04 08:46 UTC, iljaweis commented
Thanks. ;-)